os:
  - linux
  - osx

install:
  - git clone https://github.com/markh794/mhvtl
  - cd mhvtl
  - make
  - make install
  - cd /usr/src/mhvtl-1.4/kernel
  - make
  - make install
  - cp /usr/src/mhvtl-1.4/etc/mhvtl /etc/rc.d/rc.mhvtl
