os:
  - linux
  - osx
  
sudo: required

install:
  - git clone https://github.com/markh794/mhvtl
  - cd mhvtl
  - make
  - sudo make install
  - cd /usr/src/mhvtl-1.4/kernel
  - make
  - sudo make install
  - cp /usr/src/mhvtl-1.4/etc/mhvtl /etc/rc.d/rc.mhvtl
