os:
  - linux
  
sudo: required

install:
  - mkdir $HOME/src 
   
  - sudo groupadd -r vtl 
  - sudo useradd -r -c "Virtual Tape Library" -d /opt/mhvtl -g vtl vtl -s /bin/bash 
  - sudo mkdir -p /opt/mhvtl 
  - sudo mkdir -p /etc/mhvtl 
  - sudo chown -Rf vtl:vtl /opt/mhvtl 
  - sudo chown -Rf vtl:vtl /etc/mhvtl 


  - cd $HOME/src/ 
  - git clone http://github.com/markh794/mhvtl.git
  - cd mhvtl 
  - make distclean 
  - cd kernel/ 
  - make && sudo make install 
  - cd .. 
  - make && sudo make install 


  - sudo mkdir /etc/tgt 
  - sudo ln -s /usr/lib64/libvtlscsi.so /usr/lib/ 
  - sudo service mhvtl start 
