name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Install
        run: |
          sudo apt update
          sudo apt install -y virtualbox
          curl -O https://releases.hashicorp.com/vagrant/2.2.6/vagrant_2.2.6_x86_64.deb
          sudo apt install ./vagrant_2.2.6_x86_64.deb
          vagrant up
